{
 "title": "Power monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Plug",
    "query": {
     "query": "label_values(esphome_sensor_pm_watts,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Power draw [/$__interval]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "rate(esphome_sensor_integrated_joules_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - integrated"
    }
   ]
  },
  {
   "title": "Delta - expected/computed [/15m]",
   "type": "timeseries",
   "description": "Delta between integrated power and draw",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "    2\r\n  *\r\n    abs(\r\n        rate(esphome_sensor_pm_joules_total{instance=~\"$instance\"}[15m])\r\n      - on (instance)\r\n        rate(esphome_sensor_integrated_joules_total{instance=~\"$instance\"}[15m])\r\n    )\r\n/ on (instance)\r\n  (\r\n      rate(esphome_sensor_pm_joules_total{instance=~\"$instance\"}[15m])\r\n    + on (instance)\r\n      rate(esphome_sensor_integrated_joules_total{instance=~\"$instance\"}[15m])\r\n  )",
     "legendFormat": "{{instance}}%"
    },
    {
     "expr": "  rate(esphome_sensor_pm_joules_total{instance=~\"$instance\"}[15m])\r\n- on (instance)\r\n  rate(esphome_sensor_integrated_joules_total{instance=~\"$instance\"}[15m])",
     "legendFormat": "{{instance}}W"
    }
   ]
  },
  {
   "title": "Plug Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(esphome_sensor_pm_volts{instance=~\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Power draw [/${__interval}]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(rate(esphome_sensor_integrated_joules_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - integrated"
    }
   ]
  },
  {
   "title": "Power used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(esphome_sensor_integrated_joules_total{instance=~\"$instance\"}[$__range]))/3600",
     "legendFormat": "{{instance}} - integrated"
    }
   ]
  }
 ]
}